// <auto-generated />
using IDO_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDO_Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IDO_Backend.Data.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estimate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("importance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category = "Work",
                            dueDate = "2024-02-20",
                            estimate = "5 hours",
                            importance = "high",
                            name = "Complete project proposal",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 2,
                            category = "Work",
                            dueDate = "2024-02-18",
                            estimate = "3 hours",
                            importance = "medium",
                            name = "Prepare presentation slides",
                            status = "doing",
                            userId = 1
                        },
                        new
                        {
                            id = 3,
                            category = "Work",
                            dueDate = "2024-02-19",
                            estimate = "2 hours",
                            importance = "medium",
                            name = "Debug issue in code",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 4,
                            category = "Work",
                            dueDate = "2024-02-21",
                            estimate = "1.5 hours",
                            importance = "low",
                            name = "Review documentation",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 5,
                            category = "Work",
                            dueDate = "2024-02-17",
                            estimate = "1 hour",
                            importance = "low",
                            name = "Attend team meeting",
                            status = "done",
                            userId = 1
                        },
                        new
                        {
                            id = 6,
                            category = "Work",
                            dueDate = "2024-02-23",
                            estimate = "4 hours",
                            importance = "high",
                            name = "Create project plan",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 7,
                            category = "Work",
                            dueDate = "2024-02-16",
                            estimate = "2 hours",
                            importance = "medium",
                            name = "Setup development environment",
                            status = "done",
                            userId = 1
                        },
                        new
                        {
                            id = 8,
                            category = "Work",
                            dueDate = "2024-02-22",
                            estimate = "3 hours",
                            importance = "high",
                            name = "Research new technologies",
                            status = "doing",
                            userId = 1
                        },
                        new
                        {
                            id = 9,
                            category = "Work",
                            dueDate = "2024-02-24",
                            estimate = "2.5 hours",
                            importance = "medium",
                            name = "Complete training module",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 10,
                            category = "Personal",
                            dueDate = "2024-02-19",
                            estimate = "1 hour",
                            importance = "low",
                            name = "Grocery shopping",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 11,
                            category = "Hobby",
                            dueDate = "2024-02-22",
                            estimate = "2 hours",
                            importance = "medium",
                            name = "Write blog post",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 12,
                            category = "Health",
                            dueDate = "2024-02-25",
                            estimate = "1.5 hours",
                            importance = "high",
                            name = "Exercise session",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 13,
                            category = "Personal",
                            dueDate = "2024-02-18",
                            estimate = "1 hour",
                            importance = "medium",
                            name = "Read book",
                            status = "doing",
                            userId = 2
                        },
                        new
                        {
                            id = 14,
                            category = "Health",
                            dueDate = "2024-02-20",
                            estimate = "1.5 hours",
                            importance = "high",
                            name = "Attend yoga class",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 15,
                            category = "Personal",
                            dueDate = "2024-02-24",
                            estimate = "4 hours",
                            importance = "high",
                            name = "Plan weekend trip",
                            status = "doing",
                            userId = 2
                        },
                        new
                        {
                            id = 16,
                            category = "Personal",
                            dueDate = "2024-02-26",
                            estimate = "2 hours",
                            importance = "medium",
                            name = "Review personal finances",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 17,
                            category = "Career",
                            dueDate = "2024-02-23",
                            estimate = "1.5 hours",
                            importance = "medium",
                            name = "Update resume",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 18,
                            category = "Personal",
                            dueDate = "2024-02-28",
                            estimate = "3 hours",
                            importance = "high",
                            name = "Research vacation destinations",
                            status = "toDo",
                            userId = 3
                        },
                        new
                        {
                            id = 19,
                            category = "Personal",
                            dueDate = "2024-02-27",
                            estimate = "2 hours",
                            importance = "medium",
                            name = "Plan family outing",
                            status = "doing",
                            userId = 3
                        },
                        new
                        {
                            id = 20,
                            category = "Career",
                            dueDate = "2024-02-21",
                            estimate = "2.5 hours",
                            importance = "high",
                            name = "Attend networking event",
                            status = "toDo",
                            userId = 3
                        },
                        new
                        {
                            id = 21,
                            category = "Education",
                            dueDate = "2024-02-26",
                            estimate = "4 hours",
                            importance = "high",
                            name = "Complete online course",
                            status = "toDo",
                            userId = 3
                        },
                        new
                        {
                            id = 22,
                            category = "Personal",
                            dueDate = "2024-02-20",
                            estimate = "1.5 hours",
                            importance = "medium",
                            name = "Cook dinner for family",
                            status = "toDo",
                            userId = 3
                        },
                        new
                        {
                            id = 23,
                            category = "Personal",
                            dueDate = "2024-02-22",
                            estimate = "2 hours",
                            importance = "medium",
                            name = "Research new recipes",
                            status = "doing",
                            userId = 3
                        },
                        new
                        {
                            id = 24,
                            category = "Personal",
                            dueDate = "2024-02-25",
                            estimate = "3 hours",
                            importance = "low",
                            name = "Organize home office",
                            status = "toDo",
                            userId = 3
                        },
                        new
                        {
                            id = 25,
                            category = "Family",
                            dueDate = "2024-02-23",
                            estimate = "1 hour",
                            importance = "medium",
                            name = "Attend parent-teacher meeting",
                            status = "toDo",
                            userId = 3
                        });
                });

            modelBuilder.Entity("IDO_Backend.Data.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            email = "tarekhazouri@example.com",
                            password = "tarekhazouri123"
                        },
                        new
                        {
                            userId = 2,
                            email = "houssamsabih@example.com",
                            password = "houssamsabih123"
                        },
                        new
                        {
                            userId = 3,
                            email = "majdghoche@example.com",
                            password = "majdghoche123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
